apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dtol-cronjob
spec:
  schedule: "* 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            ms: dtol-cronjob
        spec:
          restartPolicy: OnFailure
          containers:
            - name: main
              image: alexeyebi/dtol-cronjob